on:
  push:
    branches:
      - development

jobs:
  build:
    runs-os: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.niniwebsite }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
